/*package drools;

import com.drools.Product;
import com.drools.Person;
import com.drools.Address;
import java.util.ArrayList;

rule "accumulate-example"

when

	accumulate(	$person:Person($age:age>40);
	
				$min:min($age),
				$max:max($age),
				$avg:average($age),
				$count:count($age)
				//$avg>25
				)
 	
then
		
	//System.out.println("No of persons with age greater than 40 "+$size);	
	System.out.println("min "+$min);
	System.out.println("max "+$max);
	System.out.println("avg "+$avg);
	System.out.println("count "+$count);
	
end
*/