/*package drools;

import com.drools.Product;
import com.drools.Person;


rule "insert-example-rule"
when
    
   $product:Product($productPrice:productPrice>50000,productName=="Laptop") 
   Person(userType=="Regular")

then
   	System.out.println("insert-example-rule invoked");
    $product.setDiscount(0.1*$productPrice);
    insert(new Product("iphone",40000));
end


rule "print-product-details"
when
	$product:Product()
then
	System.out.println("print-product-details rule invoked..");
	System.out.println("product name::"+$product.getProductName());
	System.out.println("product price::"+$product.getProductPrice());
	System.out.println("discount::"+$product.getDiscount());

end*/