/*package drools;

import com.drools.Product;

rule "discount-rule"
no-loop true
when
 	$product:Product($productPrice:productPrice > 50000,productName=="mobile")

then
	
	System.out.println("modifying mobile price");
	modify($product)
	{
	setProductPrice($productPrice+10000);
	}
	$product.setDiscount(0.10*$productPrice);
end

rule "print-product-details"
when
 	$product:Product($productPrice:productPrice)

then
    System.out.println("print-product-details invoked");
	System.out.println("productName-->"+$product.getProductName());
	System.out.println("productPrice-->"+$product.getProductPrice());
	System.out.println("discount-->"+$product.getDiscount());
	
end*/