/*package drools;

import com.drools.Product;
import com.drools.Person;

rule "print-product-details"
salience 10
when
	$product:Product()
then
	System.out.println("print-product-details invoked..");
	System.out.println("product name::"+$product.getProductName());
	System.out.println("product price::"+$product.getProductPrice());
	System.out.println("discount::"+$product.getDiscount());

end

rule "discount-rule"
salience -20
when
    
   $product:Product($productPrice:productPrice>50000) 
   Person(userType=="Regular")

then
    System.out.println("discount-rule invoked");
    $product.setDiscount(0.1*$productPrice);
    
end*/

